# Provider Service
kind: Service
apiVersion: v1
metadata:
  name: provider
spec:
  selector:
    app: provider
  type: NodePort
  ports:
    - port: 9001
      nodePort: 30169
      targetPort: 9001
---
# Provider Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider
  labels:
    app: provider
spec:
  replicas: 2
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
        - name: provider
          image: provider:14.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001
          env:   #Env Variables
          - name: DB_HOST   # Database host address from configMap
            valueFrom: 
              configMapKeyRef:
                name: db-conf  #configMap
                key: host
          - name: DB_NAME  #Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf 
                key: name
          - name: DB_USERNAME  #Database username from Secret
            value: root
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-root-credentials #db-credentials
                key: password