# Order Service
kind: Service
apiVersion: v1
metadata:
  name: order
spec:
  selector:
    app: order
  type: NodePort
  ports:
    - port: 9007
      nodePort: 30170
      targetPort: 9007
---
# Order Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: order:6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9007
          env:   #Env Variables
          - name: DB_HOST   # Database host address from configMap
            valueFrom: 
              configMapKeyRef:
                name: db-conf  #configMap
                key: host
          - name: DB_NAME  #Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf 
                key: name
          - name: DB_USERNAME  #Database username from Secret
            value: root
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-root-credentials #db-credentials
                key: password